apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
spec:
  generators:
  - list:
      elements:
      - namespace: example-namespace-1
        requests.cpu: '1'
        requests.memory: 1Gi
        limits.cpu: '2'
        limits.memory: 2Gi
      - namespace: example-namespace-2
        requests.cpu: '2'
        requests.memory: 4Gi
        limits.cpu: '4'
        limits.memory: 8Gi
  template:
    metadata:
      name: "{{namespace}}-limits"
      namespace: "{{namespace}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/jland-redhat/application-set-examples.git
        targetRevision: HEAD
        path: "kustomize/base"
        kustomize:
          patches:
          - target:
              kind: ResourceQuota
              name: namespace-quota
            patch: |-
              - op: replace
                path: /spec/hard/requests.cpu
                value: {{requests.cpu}}
              - op: replace
                path: /spec/hard/requests.memory
                value: {{requests.memory}}
              - op: replace
                path: /spec/hard/limits.cpu
                value: {{limits.cpu}}
              - op: replace
                path: /spec/hard/limits.memory
                value: {{limits.memory}}
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true