apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/jland-redhat/application-set-examples.git
      revision: HEAD
      directories:
      - path: junk_drawer/helm_charts/*
  template:
    metadata:
      name: "{{.path.basename}}"
      namespace: "junk-drawer"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/jland-redhat/application-set-examples.git
        targetRevision: HEAD
        path: "junk_drawer/helm_charts/{{.path.basename}}"
      destination:
        name: in-cluster
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true