apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
spec:
  hard:
    requests.cpu: {{ .Values.requests.cpu | quote }}
    requests.memory: {{ .Values.requests.memory }}
    limits.cpu: {{ .Values.limits.cpu | quote }}
    limits.memory: {{ .Values.limits.memory }}
