apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
spec:
  generators:
  - list:
      elements:
      - namespace: example-namespace-2
        requests.cpu: '1'
        requests.memory: 1Gi
        limits.cpu: '2'
        limits.memory: 2Gi
      - namespace: example-namespace-3
        requests.cpu: '2'
        requests.memory: 4Gi
        limits.cpu: '4'
        limits.memory: 8Gi
  template:
    metadata:
      name: "{{namespace}}-limits"
      namespace: "{{namespace}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/jland-redhat/application-set-examples.git
        targetRevision: HEAD
        path: "helm/chart"
        helm:
          parameters:
            - name: requests.cpu
              value: "{{requests.cpu}}"
            - name: requests.memory
              value: "{{requests.memory}}"
            - name: limits.cpu
              value: "{{limits.cpu}}"
            - name: limits.memory
              value: "{{limits.memory}}"
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true